blank_issues_enabled: false
contact_links:
  - name: Tributary Telegram
    url: https://t.me/tributaryso
    about: Please join our Telegram for support and discussions.
  - name: Tributary Website
    url: https://tributary.so
    about: Check out our official website for more information.
